[package]
edition = "2021"
name = "handler"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["rt", "macros", "rt-multi-thread"]}
warp = "0.3"
