#!/bin/bash
# Install all dependencies to run the project
# NOTE: requires conda
# Then install pytorch, transformers
# Then go into other dirs and install all requirements.txt
# Usage: in /Backend, run `source scripts/install-dependencies`

get_dirs() {
    COMMAND = "$((ls -d */))"
    dir_array = ("$COMMAND")
}

install_requirements() {
    get_dirs
    for dir in $dir_array; do
        cd dir && conda install --file requirements.txt && pip install -r requirements.txt
        cd ..
    done
}

conda create backend_env
install_requirements
