[package]
name = "frontend-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2.3", features = ["web"] }
wasm-bindgen = "0.2.80"
im-rc = "15.0.0"
